version: '3.8'
services:  
  kafka-connect:
    image: kafka-connect-mysql:5.5.1
    container_name: connect_mysql_kafka
    ports:
      - "${CONNECT_PORT}:${CONNECT_PORT}"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: host.docker.internal:9092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"      
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO" #DEBUG, ERROR
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      HOST: ${HOST}
      PORT: ${PORT}
      MSL_USERNAME: ${MSL_USERNAME}
      MSL_PASSWORD: ${MSL_PASSWORD}
      DBLIST: ${DBLIST}
    volumes:
      - ./run-kafka-connect.sh:/etc/kafka/run-kafka-connect.sh
    command:
      - bash
      - -c
      - |
        chmod +x /etc/kafka/run-kafka-connect.sh
        /etc/kafka/run-kafka-connect.sh